name: weather_app
description: "Basic weather app project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  provider: ^6.1.2
  google_fonts: ^6.2.1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - .env
  uses-material-design: true